import { Project } from "@/types/project";

export const projects: Project[] = [
  {
    id: "1",
    title: "Swadesh Chitra",
    description: "A high-performance full-stack news portal featuring real-time updates and a custom content management system.",
    longDescription: "Swadesh Chitra is a modern news delivery platform designed for high traffic and rapid content updates. It features a custom-built CMS that allows editors to publish in real-time with automated SEO optimization.",
    tech: ["Next.js", "MongoDB", "Tailwind CSS", "Motion"],
    image: "/assets/projects/swadesh.png",
    category: "Full Stack",
    featured: true,
    link: "https://swadeshchitra.com",
    role: "Lead Full Stack Developer",
    outcome: "Increased site performance by 40% and improved editorial workflow efficiency by 25%.",
    challenges: "Handling high-concurrency during peak news hours and implementing a real-time caching strategy.",
  },
  {
    id: "2",
    title: "Project Alpha",
    description: "Modern dashboard for data visualization and analytics.",
    longDescription: "Project Alpha provides real-time insights into business metrics through interactive charts and predictive analytics models.",
    tech: ["React", "D3.js", "Supabase"],
    image: "/assets/projects/alpha.png",
    category: "Dashboard",
    featured: false,
    role: "Frontend Engineer",
    outcome: "Reduced data reporting latency for the client from minutes to sub-second updates.",
  },
  {
    id: "3",
    title: "Zenith UI",
    description: "A minimalist component library focused on accessibility and motion.",
    longDescription: "Zenith UI is a collection of high-quality, accessible React components designed to help developers build beautiful interfaces faster.",
    tech: ["TypeScript", "Radix UI", "Tailwind"],
    image: "/assets/projects/zenith.png",
    category: "UI System",
    featured: false,
    role: "UI Engineer",
    outcome: "Adopted by 3 internal teams, reducing UI development time by 30%.",
  },
  {
    id: "4",
    title: "Lumina",
    description: "Content-driven platform for digital creators with seamless media handling.",
    longDescription: "Lumina is a media-rich platform that allows creators to showcase their work in a high-fidelity environment with optimized delivery.",
    tech: ["Next.js", "Sanity.io", "Cloudinary"],
    image: "/assets/projects/lumina.png",
    category: "Platform",
    featured: true,
    role: "Frontend Lead",
    outcome: "Achieved a 98+ Lighthouse score for performance and accessibility.",
  },
];
